import "./globals.css";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  let userLoggedIn = false;
  if (cookies().get("my-refresh-token")) {
    userLoggedIn = true;
  }

  return (
    <html lang="en">
      <body className={`${inter.className} h-screen w-screen flex flex-col`}>
        <Header userLoggedIn={userLoggedIn} />
        <main className="grow flex flex-col items-center justify-center bg-zinc-900 text-stone-300">
          {children}
        </main>
      </body>
    </html>
  );
}
